export const createLikeType='like/create/post'
export const getLikeType='like/get/post'
export const deleteLikeType='like/delete/post'
export const createLikeCommentType='like/create/comment'
export const getLikeCommentType='like/get/comment'
export const deleteLikeCommentType='like/delete/comment'